### ISSUE TITLE
error when current timestamp begins earlier than the previous timestamp

### ISSUE THREAD

**Issue by rococodogs** [LafayetteCollegeLibraries/webvtt-cli#6]
(in this example, let's pretend i entered "48" instead of "58" as intended).

```csv
Timestamp,Speaker,Text
00:29:54–00:29:58,Interviewer,"OK. So, Winston, are you married? ",
00:29:48–00:29:49,Speaker,Yes. Yes I am.,
```

**Comment by jacksodl23** [comment]
This should work since the timestamp is converted into seconds for comparison with the previous timestamp. The program will output a message stating that the start timestamp must be greater than or equal to the start of the previous cue.
